version: '3.8'

services:
  web:
    build: 
        context: ./
        dockerfile: Dockerfile.prod
    command: gunicorn -b :80 --access-logfile - --error-logfile - server:app
    ports:
      - 80:80
    env_file:
      - ./.env.prod
    depends_on:
    - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    env_file:
    - ./.env.prod.db
    ports:
      - 6543:5432
# networks:
#   my_docker_network:
#     driver: bridge
#     ipam:
#       config:
#         - subnet: 10.5.0.0/16
volumes:
  postgres_data_prod: