version: '3.8'

services:
  web:
    build: ./
    command: gunicorn -b :8080 --access-logfile - --error-logfile - server:app
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8080:8080
    env_file:
      - ./.env.dev
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=alexandre
      - POSTGRES_PASSWORD=Abc123
      - POSTGRES_DB=vega
    ports:
      - 6543:5432
networks:
  my_docker_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
volumes:
  postgres_data: