version: '3.8'

services:
  web:
    build: ./
    command: flask run -h 0.0.0.0 -p 5000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=alexandre
      - POSTGRES_PASSWORD=Abc123
      - POSTGRES_DB=vega

volumes:
  postgres_data: